---
- name: Sysbench
  hosts: sysbench
  become: true

  tasks:
    - name: Install sysbench
      when: inventory_hostname in groups['sysbench']
      block:
        - name: Download MariaDB repo setup script
          ansible.builtin.get_url:
            url: https://dlm.mariadb.com/3/MariaDB/mariadb_repo_setup
            dest: /tmp/mariadb_repo_setup
            mode: "0755"
        - name: Execute MariaDB repo setup script
          ansible.builtin.command: /tmp/mariadb_repo_setup --mariadb-server-version={{ mariadb_version }}
          args:
            creates: /etc/yum.repos.d/MariaDB.repo
        - name: Install MariaDB Client
          ansible.builtin.package:
            name: MariaDB-client
            state: present
        - name: Ensure EPEL repository is installed
          ansible.builtin.yum:
            name: epel-release
            state: present
        - name: Install sysbench
          ansible.builtin.yum:
            name: sysbench
            state: present

    - name: Print sysbench command
      ansible.builtin.debug:
        msg: |
          5M records is 1.2GB
          sysbench /usr/share/sysbench/oltp_read_write.lua \
            --db-driver=mysql \
            --mysql-user=root \
            --mysql-password=root_pass \
            --mysql-db=test \
            --mysql-host=node1 \
            --tables=5 \
            --table-size=5000000 \
            prepare
          sysbench /usr/share/sysbench/oltp_read_write.lua \
            --db-driver=mysql \
            --mysql-user=root \
            --mysql-password=root_pass \
            --mysql-db=test \
            --mysql-host=node1 \
            --tables=5 \
            --table-size=5000000 \
            --threads=4 \
            --time=60 \
            --report-interval=10 \
            run
