---
- name: Shutdown All Servers
  hosts: all
  become: true
  gather_facts: false

  vars_prompt:
    - name: "confirmation"
      prompt: "Are you sure you want to shutdown ALL servers? This action cannot be undone. (yes/no)"
      private: false

  tasks:
    - name: Confirm shutdown
      ansible.builtin.fail:
        msg: "Shutdown aborted by user."
      when: confirmation != "yes"
      changed_when: false

    - name: Shutdown the server
      ansible.builtin.shell: "shutdown -h +1 'Ansible initiated shutdown'"
      ignore_errors: true
