---
- name: Shutdown All Servers
  hosts: all
  become: yes
  gather_facts: no

  vars_prompt:
    - name: "confirmation"
      prompt: "Are you sure you want to shutdown ALL servers? This action cannot be undone. (yes/no)"
      private: no

  tasks:
    - name: Confirm shutdown
      ansible.builtin.fail:
        msg: "Shutdown aborted by user."
      when: confirmation != "yes"
      changed_when: false

    - name: Shutdown the server
      ansible.builtin.command:
        cmd: shutdown -h +1 "Ansible initiated shutdown"
      async: 0
      poll: 0
      ignore_errors: true
