---
- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    aws_region: ap-southeast-1
    instance_type: t3.micro
  tasks:
    - name: Lookup latest Amazon Linux 2023 AMI
      ec2_ami_info:
        region: "{{ aws_region }}"
        owners: "amazon"
        filters:
          name: "amzn2-ami-hvm-*-gp2"
          architecture: "x86_64"
          state: "available"
          root-device-type: "ebs"
      register: ami_info

    - name: Provision EC2 instance
      ec2_instance:
        name: "TestInstance"
        image_id: "{{ ami_info.images | sort(attribute='creation_date') | last | json_query('image_id') }}"
        instance_type: "{{ instance_type }}"
        region: "{{ aws_region }}"
        network:
          assign_public_ip: no
      register: ec2

    - name: Print instance ID
      debug:
        msg: "{{ ec2.instance_ids }}"

    - name: Destroy the instance
      ec2_instance:
        state: "absent"
        instance_ids: "{{ ec2.instance_ids }}"
        region: "{{ aws_region }}"
